name: geog124_env

dependencies:
    - python=3.6
    - jupyter
    - numpy
    - scipy
    - matplotlib
    - ipywidgets
    - pandas
    - nbpresent
    - jupyter_contrib_nbextensions
    - traitlets>=4.3.1
    - ipython
    - vdom
    - jupyterlab_launcher>=0.5.0
